#pragma once



#define START_TITLE_SCREEN_EVENT ALLEGRO_GET_EVENT_TYPE('T','T','L','E')
#define START_GAME_PLAY_EVENT    ALLEGRO_GET_EVENT_TYPE('G','M','P','L')
#define QUIT_GAME_EVENT          ALLEGRO_GET_EVENT_TYPE('Q','U','I','T')



